config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  devise_for :users
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :shows
  get 'press', to: 'static_pages#press'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :user

  validates :dates, presence: true
  validates :venue, presence: true
  validates :location, presence: true

  attr_reader :formatted_date

  def formatted_date
    return nil if dates.blank?
    
    # Remove any commas and clean up the string
    clean_dates = dates.gsub(',', '').strip
    
    if clean_dates.include?('-')
      # Split on the dash and take the first date
      start_date = clean_dates.split('-').first.strip
      parse_date(start_date)
    else
      parse_date(clean_dates)
    end
  end

  def start_date
    return nil if dates.blank?
    
    # Clean the date string
    clean_dates = dates.gsub(',', '').strip
    
    if clean_dates.include?('-')
      # Split on the dash and take the first date
      start_date = clean_dates.split('-').first.strip
      parse_date(start_date)
    else
      parse_date(clean_dates)
    end
  end

  def end_date
    return nil if dates.blank?
    
    clean_dates = dates.gsub(',', '').strip
    
    if clean_dates.include?('-')
      parts = clean_dates.split('-')
      start_parts = parts.first.strip.split
      end_parts = parts.last.strip.split
      
      # Check if the range has an explicit year
      if clean_dates.match(/\b\d{4}\b/)
        # Has explicit year, use the old logic
        month = start_parts[0]
        year = (end_parts.last =~ /\d{4}/) ? end_parts.last : start_parts.last
        
        # Construct the full end date
        date_str = [month, end_parts.first, year].join(' ')
        parse_date(date_str)
      else
        # No year specified, construct the end date and let parse_date handle the year logic
        month = start_parts[0]
        date_str = [month, end_parts.first].join(' ')
        parse_date(date_str)
      end
    else
      parse_date(clean_dates)
    end
  end

  def self.valid_shows
    # Since shows won't overlap, sorting by start_date gives same order as end_date
    # Using start_date as it's more intuitive when reading the dates
    self.future_shows.sort_by { |show| show.start_date || Date.new(9999) }
  end

  private

  def parse_date(date_str)
    # Check if the date string contains a 4-digit year
    if date_str.match(/\b\d{4}\b/)
      # Has explicit year, parse normally
      Date.parse(date_str)
    else
      # No year specified, assume the next occurrence of this date
      parsed_date = Date.parse("#{date_str} #{Date.current.year}")
      
      # If this date has already passed this year, assume next year
      if parsed_date < Date.current
        parsed_date = Date.parse("#{date_str} #{Date.current.year + 1}")
      end
      
      parsed_date
    end
  rescue
    nil
  end

  def self.future_shows
    # Use end_date for determining if a show is in the future
    # This keeps shows visible until they're completely over
    # Handle nil dates gracefully by excluding them
    all.select { |show| show.end_date && show.end_date >= Date.current }
  end

  def self.past_shows
    # Handle nil dates gracefully by excluding them
    all.select { |show| show.end_date && show.end_date < Date.current }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
  has_many :shows
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  # GET /shows
  def index
    @shows = Show.all
  end

  # GET /shows/1
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  def create
    @show = current_user.shows.new(show_params)

    if @show.save
      redirect_to @show, notice: 'Show was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /shows/1
  def update
    if @show.update(show_params)
      redirect_to @show, notice: 'Show was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /shows/1
  def destroy
    @show.destroy
    redirect_to shows_url, notice: 'Show was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def show_params
      params.require(:show).permit(:dates, :venue, :location, :link, :note)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'static'

  def index
    @shows = Show.valid_shows
  end

  def press
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
    analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    analytics.page();
    }}();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-166068414-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-166068414-1');
  </script>

  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
  <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
  <link href="/assets/tailwind.css" rel="stylesheet">
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>
<body>
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
</body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Brendan Eyre</title>
  <meta name="description" content="" />
  <meta name="keywords" content="Brendan Eyre, comedy, comedian, standup, standup comedy, new york city, NYC, New York City Standup, New York City comedy, nyc comedy, nyc comedian, nyc standup, nyc standup comedian, new york city standup comedian" />
  <meta name="author" content="bgricker">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
  <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->

  <!-- Favicons -->
  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
  <link rel="icon" type="image/png" href="/favicon.png" />
  <link rel="apple-touch-icon" href="/apple-touch-icon.png" />

  <!-- Original Theme CSS -->
  <link href="/css/style.css" rel="stylesheet" type="text/css" />
  <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
  <link href="/css/plugins/animate.css" rel="stylesheet" type="text/css" />

  <%# Rails helpers for CSRF - still good practice %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

</head>
<body class="wow-animate">

  <%= yield %>

  <!-- Original Theme JS -->
  <script src="/js/jquery-1.11.3.min.js" type="text/javascript"></script>
  <script src="/js/plugins/jquery.easing.js" type="text/javascript"></script>
  <script src="/js/plugins/SmoothScroll.js" type="text/javascript"></script>
  <script src="/js/plugins/owl.carousel.min.js" type="text/javascript"></script>
  <script src="/js/plugins/wow.min.js" type="text/javascript"></script>
  <script src="/js/plugins/isotope.pkgd.min.js" type="text/javascript"></script>
  <script src="/js/plugins/jquery.stellar.min.js" type="text/javascript"></script>
  <script src="/js/plugins/jquery.fitvids.js" type="text/javascript"></script>
  <script src="/js/plugins/jquery.magnific-popup.min.js" type="text/javascript"></script>
  <script src="/js/plugins/jquery.appear.js" type="text/javascript"></script>
  <script src="/js/plugins/jquery.countTo.js" type="text/javascript"></script>
  <script src="/js/plugins/jquery.mb.YTPlayer.min.js" type="text/javascript"></script>
  <script src="/js/plugins/jquery.simple-text-rotator.min.js" type="text/javascript"></script>
  <script src="/js/plugins/jquery.backstretch.js" type="text/javascript"></script>
  <script src="/js/plugins/jquery.singlePageNav.min.js" type="text/javascript"></script>
  <script src="/js/plugins/jquery.validate.min.js" type="text/javascript"></script>
  <script src="/js/send-subscribe.js" type="text/javascript"></script>
  <script src="/js/contact-form.js" type="text/javascript"></script>
  <%# <script src="http://maps.google.com/maps/api/js?sensor=false&amp;language=en" type="text/javascript"></script> %>
  <%# <script src="/js/map.js" type="text/javascript"></script> %>
  <script src="/js/theme.js" type="text/javascript"></script>

</body>
</html> 

app/views/shows/_form.html.erb
<%= simple_form_for(@show) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    Single date show: "January 1 2026"<br>
    Multiple date show: "October 25 - 31 2026"
    <%= f.input :dates %>
    <%= f.input :venue %>
    <%= f.input :location %>
    <%= f.input :link %>
    <%= f.input :note %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<%= link_to 'Home', root_path %>

<p id="notice"><%= notice %></p>

<h1>Shows</h1>

<table>
  <thead>
    <tr>
      <th>Dates</th>
      <th>Venue</th>
      <th>Location</th>
      <th>Link</th>
      <th>Note</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shows.each do |show| %>
      <tr>
        <td><%= show.dates %></td>
        <td><%= show.venue %></td>
        <td><%= show.location %></td>
        <td><%= show.link %></td>
        <td><%= show.note %></td>
        <td></td>
        <td><%= link_to 'Show', show %></td>
        <td><%= link_to 'Edit', edit_show_path(show) %></td>
        <td><%= link_to 'Destroy', show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Show', new_show_path %>

app/views/shows/new.html.erb
<div class="container mt-50 center">
  <h2 class="mb-60">New Show</h2>

  <%= render 'form', show: @show %>
</div>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dates:</strong>
  <%= @show.dates %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @show.venue %>
</p>

<p>
  <strong>Location:</strong>
  <%= @show.location %>
</p>

<p>
  <strong>Link:</strong>
  <%= @show.link %>
</p>

<p>
  <strong>Note:</strong>
  <%= @show.note %>
</p>

<%= link_to 'Edit', edit_show_path(@show) %> |
<%= link_to 'Back', shows_path %>

app/views/static_pages/index.html.erb
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Brendan Eyre</title>
    <meta name="description" content="" />
    <meta name="keywords" content="Brendan Eyre, comedy, comedian, standup,
    standup comedy, new york city, NYC, New York City Standup, New York City
    comedy, nyc comedy, nyc comedian, nyc standup, nyc standup comedian, new
    york city standup comedian" />
    <meta name="author" content="bgricker">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->

    <!-- Favicone Icon -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico" />
    <link rel="icon" type="image/png" href="img/favicon.png" />
    <link rel="apple-touch-icon" href="img/favicon.png" />

    <!-- Css -->
    <link href="css/style.css" rel="stylesheet" type="text/css" />
    <link href="css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="css/plugins/animate.css" rel="stylesheet" type="text/css" />
  </head>
  <body class="wow-animate">


    <!-- Page Wraper -->
    <div id="page-wraper">

      <!-- Header -->
      <header id="header" class="header">
        <div class="header-inner">

          <!-- Mobile Navbar Icon -->
          <div class="nav-mobile nav-bar-icon">
            <span></span>
          </div>
          <!-- End Mobile Navbar Icon -->

          <!-- Navbar Navigation -->
          <div class="nav-menu singlepage-nav">
            <ul class="nav-menu-inner">
              <li><%= link_to "Home", root_path(anchor: "intro") %></li>
              <li><%= link_to "About", root_path(anchor: "about") %></li>
              <li><%= link_to "Shows", root_path(anchor: "shows") %></li>
              <li><%= link_to "TikTok", "https://www.tiktok.com/@RealBrendanEyre", target: "_blank", rel: "noopener", class: "no-scroll" %></li>
              <li><%= link_to "Instagram", "https://www.instagram.com/eyrebud/?hl=en", target: "_blank", rel: "noopener", class: "no-scroll" %></li>
              <li><%= link_to "Press", press_path, class: "no-scroll" %></li>
              <% if current_user %>
                <li><%= link_to "New Show", new_show_path, class: "no-scroll" %></li>
                <li><%= link_to "Shows", shows_path, class: "no-scroll" %></li>
              <% end %>
            </ul>
          </div>
          <!-- End Navbar Navigation -->

        </div>
      </header>
      <!-- End Header -->

      <!-- Intro -->
      <section id="intro" class="intro black-bg">
        <!-- Slider -->
        <div class="fullscreen-slider owl-carousel white owl-theme-1">
          <div class="item">
              <div class="slide-bg-image overlay-dark40 dark-bg parallax parallax-section bg-no-repeat bg-top bg-center bg-cover h-screen"
  style="background-image: url('/img/full/01.jpg'); background-position: top center !important;">
              <div class="js-fullscreen-height container">
                <div class="intro-content">
                  <div class="intro-content-inner">
                    <h1 class="intro-title mb-50">Brendan Eyre</h1>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- End Slider -->
      </section>
      <!-- End Intro -->

      <!-- About Section -->
      <section id="about" class="section-padding">
        <div class="container text-center mb-60">
          <h1>About Brendan</h1>
          <p class="lead-lg max-width-700">Brendan Eyre is one of the country's top club and corporate event comedians. His laid back, relatable style has proven a hit with audiences all over the world. He has appeared on Late Night with Seth Meyers on NBC, Comedy Central, Gotham Comedy Live, and his comedy has been viewed over 50 million times on TikTok. He was also a New Face of Comedy at the prestigious Just For Laughs comedy festival and he is heard regularly on Sirius XM radio. 
</p></br></br></br>
          <div class="responsive-video">
            <iframe src="https://player.vimeo.com/video/319537174" width="100%"
                                                                  frameborder="0" webkitallowfullscreen
                                                                              mozallowfullscreen allowfullscreen></iframe>
          </div>

          <div class="responsive-video">
            <iframe width="100%" src="https://www.youtube.com/embed/srdJI4qC7SQ?si=BCj-HByV5HqqOmtw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
          </div>

          <div class="responsive-video">
            <iframe width="100%" src="https://www.youtube.com/embed/hgxfDWp1Clc?si=tjje71-zTjONBwb7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
          </div>
        </div>
      </section>
      <!-- End About Section -->

      <hr />

      <!-- History Section -->
      <section id="shows" class="section-padding">
        <div class="container text-center">
          <h1 class="mb-60">Shows</h2>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <% if @shows.any? %>
              <% @shows.each do |show| %>
                <%= link_to show.link do %>
                  <div class="history-box mb-30">
                    <h6 class="alt-title history-year"><%= show.dates %></h6>
                    <h4 class="alt-title history-title"><%= show.venue %> <%= show.location %></h4>
                  </div>
                <% end %>
              <% end %>
            <% else %>
                  <h3 class="mb-60">No shows scheduled for now</h2>
            <% end %>
            </div>
          </div>
        </div>
      </section>
      <!-- End History Section -->



      <!-- Contact Infobar Section -->
      <section class="ptb-60 black-bg text-center dark-bg">
        <div class="container">
          <div class="col-md-12 col-sm-12 mb-sm-30">
            <div class="contact-info">
              <a href="mailto:brendaneyre@gmail.com">
                <div class="alt-icon-top alt-icon-color">
                  <i class="icon-envelope"></i>
                </div>
                <p class="large">brendaneyre@gmail.com</p>
              </a>
            </div>
          </div>
        </div>
      </section>
      <!-- End Contact Infobar Section -->

      <!-- Footer Section -->
      <footer id="footer" class="footer gray-bg">
        <div class="container text-center">
          <ul class="social mb-60 wow fadeInUp" data-wow-duration="1.5s">
            <li>
              <a target="_blank" href="https://www.facebook.com/brendan.eyre.16"><i class="fa fa-facebook"></i></a>
            </li>
            <li>
              <a target="_blank" href="https://twitter.com/eyrebud?lang=en"><i class="fa fa-twitter"></i></a>
            </li>
            <li>
              <a target="_blank" href="https://www.instagram.com/eyrebud/?hl=en"><i class="fa fa-instagram"></i></a>
            </li>
          </ul>
          <p class="copyright">
          <a class="copy-link scroll-top" href="">&copy; Brendan Eyre
            2025</a><br />
          All Rights Reserved
          </p>
        </div>
      </footer>
      <!-- End Footer Section -->

    </div>
    <!-- End Page Wraper -->



    <!-- JS Script -->
    <script src="js/jquery-1.11.3.min.js" type="text/javascript"></script>
    <script src="js/plugins/jquery.easing.js" type="text/javascript"></script>
    <script src="js/plugins/SmoothScroll.js" type="text/javascript"></script>
    <script src="js/plugins/owl.carousel.min.js" type="text/javascript"></script>
    <script src="js/plugins/wow.min.js" type="text/javascript"></script>
    <script src="js/plugins/isotope.pkgd.min.js" type="text/javascript"></script>
    <script src="js/plugins/jquery.stellar.min.js" type="text/javascript"></script>
    <script src="js/plugins/jquery.fitvids.js" type="text/javascript"></script>
    <script src="js/plugins/jquery.magnific-popup.min.js" type="text/javascript"></script>
    <script src="js/plugins/jquery.appear.js" type="text/javascript"></script>
    <script src="js/plugins/jquery.countTo.js" type="text/javascript"></script>
    <script src="js/plugins/jquery.mb.YTPlayer.min.js" type="text/javascript"></script>
    <script src="js/plugins/jquery.simple-text-rotator.min.js" type="text/javascript"></script>
    <script src="js/plugins/jquery.backstretch.js" type="text/javascript"></script>
    <script src="js/plugins/jquery.singlePageNav.min.js" type="text/javascript"></script>
    <script src="js/plugins/jquery.validate.min.js" type="text/javascript"></script>
    <script src="js/send-subscribe.js" type="text/javascript"></script>
    <script src="js/contact-form.js" type="text/javascript"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=false&amp;language=en" type="text/javascript"></script>
    <script src="js/map.js" type="text/javascript"></script>
    <script src="js/theme.js" type="text/javascript"></script>

  </body>

app/views/static_pages/press.html.erb
<div class="container mx-auto px-4 py-8">
  <h1 class="text-4xl font-bold mb-8">Press</h1>
  
  <div class="prose max-w-none">
    <p class="text-lg mb-6">
      For press inquiries, please contact us at <a href="mailto:press@brendaneyre.com" class="text-blue-600 hover:text-blue-800">press@brendaneyre.com</a>
    </p>
  </div>
</div> 